<a href="https://colab.research.google.com/github/youngseo21/esaa_22/blob/main/100_Numpy_exercises_1-25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


In [85]:
!pip install generators
import numpy as np

import generators as ge


def question(n):
    print(f'{n}. ' + ge.QHA[f'q{n}'])


def hint(n):
    print(ge.QHA[f'h{n}'])


def answer(n):
    print(ge.QHA[f'a{n}'])


def pick():
    n = np.random.randint(1, 100)
    question(n)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


#### 1. Import the numpy package under the name `np` (★☆☆)

In [7]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [8]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
null = np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [16]:
null.itemsize

8

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
null = np.zeros(10)
null[4] = 1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
six = np.arange(10,50)
print(six)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [26]:
print(six[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
eight = np.arange(0,9).reshape(3,3)
eight

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [25]:
nine = np.array([1,2,0,0,4,0])
print(np.where(nine != 0))

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [28]:
ten_identity = np.identity(3)
ten_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
ten_eye = np.eye(3, dtype = int)
ten_eye

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [34]:
eleven = np.random.random((3,3,3))
eleven

array([[[0.75991629, 0.70561144, 0.00874088],
        [0.43388093, 0.03803645, 0.66555559],
        [0.98080648, 0.02270383, 0.31315026]],

       [[0.09429683, 0.33874701, 0.05948302],
        [0.52406098, 0.04834236, 0.62819988],
        [0.36579866, 0.75668131, 0.387893  ]],

       [[0.91402132, 0.39879821, 0.61724981],
        [0.9971554 , 0.59249165, 0.83761927],
        [0.65208371, 0.94179146, 0.43286459]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [39]:
twelve = np.random.random((10,10))
for i in twelve:
  print(np.min(i), np.max(i))

0.028599565805721316 0.8061793750153344
0.09710954408821415 0.9061006790559176
0.033273586214070394 0.9051223615574387
0.10496887192475679 0.9719731625285859
0.09748977451312968 0.932050818176352
0.09377428816156685 0.980229249252182
0.058817070777438474 0.994848894900235
0.056302767063807435 0.7495337071557461
0.07475929479371379 0.9579564256235084
0.0838260310906197 0.9578495167588048


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [41]:
thirteen = np.random.random(30)
np.mean(thirteen)

0.537265125361966

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [45]:
n = 5
x = np.ones((n,n))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [47]:
0 * np.nan

nan

In [48]:
np.nan == np.nan

False

In [49]:
np.inf > np.nan

False

In [50]:
np.nan - np.nan

nan

In [51]:
np.nan in set([np.nan])

True

In [53]:
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [56]:
sixteen = np.diag([1,2,3,4], k = -1)
sixteen

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [92]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [87]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [62]:
nineteen = np.random.rand(5,5)
(nineteen - np.mean(nineteen)) / np.std(nineteen)

array([[-1.05184549, -0.68582092, -1.14725299,  0.08065648, -1.48148318],
       [ 0.64388155, -0.16367474, -0.24658079,  0.77810241,  1.22841763],
       [ 1.47278301, -1.20486195, -1.54421254, -0.38658709,  1.53100569],
       [-0.18070473, -1.35985317,  0.95808919,  0.21511597,  1.49805231],
       [-1.32934322,  0.29175908,  0.17899394,  0.93526506,  0.9700985 ]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [63]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)]) # 몰라

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [64]:
a = np.random.random((5,3))
b = np.random.random((3,2))
np.dot(a,b)

array([[0.97497143, 0.09227209],
       [0.70979826, 0.08810528],
       [0.81206442, 0.1446568 ],
       [0.89020834, 0.13664702],
       [0.72505992, 0.28093666]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [67]:
twentytwo = np.arange(10)
twentytwo[(twentytwo>2) & (twentytwo<8)] *= (-1)

twentytwo

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [68]:
sum(range(5),-1)  # range()

9

In [94]:
from numpy import *
print(sum(range(5), -1))  # numpy패키지 안에 있는 sum()함수의 경우 

10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [83]:
z = [1,2,3]
z<z>z

False

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [75]:
print(np.array(0))

0


In [73]:
np.array(0) / np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [71]:
np.array(0) // np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [76]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3