<a href="https://colab.research.google.com/github/youngseo21/esaa_22/blob/main/assignment_091122(ML).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. 파이썬 기반의 머신러닝과 생태계 이해
---



## **Index**
### 01. 머신러닝의 개념
* 머신러닝의 분류

### 02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지

### 03. 넘파이
* 넘파이 ndarray 개요
* ndarray의 데이터 타입
* ndarray를 편리하게 생성하기 - `arange`, `zeros`, `ones`
* ndarray의 차원과 크기를 변경하는 `reshape()`
* 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
* 행렬의 정렬 - `sort()`와 `argsort`()
* 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
---

#01. 머신러닝의 개념
---
- **Machine Learning**: 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
- 기존에는 매우 복잡한 현실 세계의 조건들로 인해 해결하기 어려웠던 문제들을 머신러닝을 이용해 해결 가능하다.
- 데이터마이닝, 영상 인식, 음성 인식, 자연어 처리에서 개발자가 데이터나 업무 로직의 특성을 직접 고려한 프로그램을 만들 때 난이도와 개발 복잡도가 너무 높아지는 문제를 머신러닝을 이용해 해결할 수 있다.

### | 머신러닝의 분류
---
*   **지도학습(Supervised Learning)**
  - 분류(Classification)
  - 회귀(Regression)
  - 그 외에도 추천 시스템; 시각/음성 감지/인지; 텍스트 분석(Text mining), 자연어 처리(NLP)

*   **비지도학습(Unsupervised Learning)**
  - 클러스터링(Clustering)
  - 차원 축소
* **강화학습(Reinforcement Learning)**

#02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지
---
* 머신러닝 패키지: 사이킷런(**Scikit-Learn**), 텐서플로, 케라스
* 행렬/선형대수/통계 패키지: 넘파이(**NumPy**), 사이파이(**SciPy**)
* 데이터 핸들링: 판다스(**Pandas**)
* 시각화: 맷플롯립(**Matplotlib**), 시본(**Seoborn**)

#03. 넘파이
---
* 머신러닝의 주요 알고리즘은 선형대수와 통계 등에 기반한다. 
* **NumPy(Numerical Python)**: 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
* 구글의 대표적인 딥러닝 프레임워크인 텐서플로는 넘파이와 호환된다. 
* 넘파이는 배열 기반의 연산뿐 아니라 다양한 데이터 핸들링 기능을 제공한다. 하지만 대표적인 데이터 처리 패키지인 판다스의 편리성에는 미치지 못한다. 
* **넘파이를 이해하는 것은 파이썬 기반의 머신러닝에서 매우 중요하다.** 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있으며, 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용하기 때문이다. 또한 판다스를 이해하는 데도 많은 도움이 된다. 

### | 넘파이 ndarray 개요
---
* 넘파이 모듈 임포트
```python
import numpy as np
```
* **ndarray**: 넘파이의 기반 데이터 타입 
  - ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행 가능
* `np.array()` 함수: list와 같은 다양한 인자를 입력 받아서 ndarray로 변환
```python
array1 = np.array(argument)
# argument = a list, tuple or any array-like object
```
* `ndarray.shape`: ndarray의 차원과 크기를 튜플 형태로 
  - array1과 array3는 동일한 차원의 데이터가 아님을 유의하자. 
  - 리스트 [ ]는 1차원, 리스트의 리스트 [[ ]]는 2차원
* `ndarray.ndim`를 이용해 각 array의 차원을 알 수 있다. 


In [2]:
import numpy as np

array1 = np.array([1,2,3]) # 3 element list
print('array1 type: ', type(array1)) 
print('array1 array 형태: ', array1.shape) # 3 data를 가진 1차원 데이터

array2 = np.array([[1,2,3], [2,3,4]]) # 2x3
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape) # 2 rows, 3 cols인 2차원 데이터

array3 = np.array([[1,2,3]]) # 1x3. 대괄호가 2개
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape) # 1 rows, 3 cols인 2차원 데이터

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


In [ ]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


### | ndarray의 데이터 타입
---
* ndarray내의 데이터값은 숫자(int형, float형), 문자열, 불(bool) 값 등 모두 가능 
* 단, ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능 (int와 float가 한 개의 ndarray 안에 함께 있을 수 없음)
* `ndarray.dtype`으로 ndarray내의 데이터 타입 확인

In [ ]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1) # list to ndarray
print(type(array1))
print(array1, array1.dtype)

print(list1, array1) # list는 comma로, ndarray는 띄어쓰기로 나뉨

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
[1, 2, 3] [1 2 3]


* 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 **데이터 크기**가 더 큰 데이터 타입으로 형 변환을 일괄 적용

In [ ]:
list2 = [1,2,'test'] # int형 값과 문자열이 섞인 리스트
array2 = np.array(list1)
print(array2, array2.dtype) # int로 통일

list3 = [1,2, 3.0] # int형과 float형이 섞인 리스트
array3 = np.array(list3)
print(array3, array3.dtype) # float로 통일

[1 2 3] int64
[1. 2. 3.] float64


* `ndarray.astype()`: ndarray내 데이터 값의 타입 변경
  - 인자에 원하는 타입을 문자열로 지정
  - 보통 대용량 데이터의 ndarray를 만들 때 메모리 절약을 위해 이용
  - 머신러닝 알고리즘에 대용량의 데이터를 로딩할 경우 수행 속도가 느려지거나 메모리 부족으로 오류 발생

In [ ]:
array_int = np.array([1,2,3])
print(array_int, array_int.dtype)

array_float = array_int.astype('float64') # int64를 float64로 변경
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32') # float64를 int32로 변경
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32') # float를 int형응로 변경
print(array_int2, array_int2.dtype) # 소수점 이하는 없어짐

[1 2 3] int64
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### | ndarray를 편리하게 생성하기 - `arange`, `zeros`, `ones`
---
* 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해야 할 때, `arange`, `zeros`, `ones`를 사용
  - 테스트용으로 데이터를 만들 경우
  - 대규모의 데이터를 일괄적으로 초기화해야 할 경우

* `np.arange()`: 지정한 범위의 값을 순차적으로 ndarray의 값으로 반환
  - range() 함수와 유사
  - default 함수 인자는 stop 값. 0부터 (n - 1)까지의 값을 순차적으로 ndarray의 데이터값으로 변환
  ```python
  np.arange(n)
  ```
  - 혹은 start값과 숫자의 간격(step) 설정 가능
  ```python
  np.arange(start, stop, step)
  ```

In [ ]:
sequence_array = np.arange(10) # 0부터 (10-1)까지
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) # 1차원

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


* `np.zeros()`: 모든 값을 0으로 채운 ndarray를 반환
  - 함수 인자로 튜플 형태의 shape 값을 입력
  ```python
  np.zeros((row, columm))
  
* `np.ones()`: 모든 값은 1로 채운 ndarray를 반환
  - 함수 인자로 튜플 형태의 shape 값을 입력
  - 함수 인자 `dtype`의 디폴트는 float64
  ```python
  np.ones((row, column, dtype = 'datatype')
  ```

In [ ]:
zero_array = np.zeros((3,2), dtype = 'int32') # 3 rows, 2 cols 
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((2,3)) # 2 rows, 3 cols, 'float64' default
print(one_array)
print(one_array.dtype, one_array.shape)

one_array1 = np.ones((2,3), dtype = 'int32') # 2 rows, 3 cols, 'int32' dtype
print(one_array1)
print(one_array1.dtype, one_array1.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1. 1.]
 [1. 1. 1.]]
float64 (2, 3)
[[1 1 1]
 [1 1 1]]
int32 (2, 3)


### | ndarray의 차원과 크기를 변경하는 `reshape()`
---
* `ndarray.reshape()`: ndarray를 특정 차원 및 크기로 변환
```python
ndarray.reshape(row, column)
```


In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5) # into 2 rows, 5 cols
print('array2:\n', array2)

array3 = array1.reshape(5,2) # into 5 rows, 2 cols
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


* 지정된 사이즈로 변경이 불가능하면 오류 발생

In [ ]:
array1.reshape(4,3) # 4x3, 12 elements needed

ValueError: ignored

* 인자로 -1를 적용할 경우 원래 ndarray와 호환되는 새로운 shape로 변환 (실전에서 더욱 효율적 사용)
  - 단, -1을 사용하더라도 호환될 수 없는 형태는 변환 불가  
  - 주로 `reshape(-1,1)`와 같은 형태로 자주 사용 
    + 원본이 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 컬럼을 가진 ndarray로 변환됨.
    + 3차원을 2차원으로, 1차원을 2차원으로 변경
    + `ndarray.tolist(_)`: ndarray를 리스트 자료형으로 변환 

In [ ]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5) # shape with 5 cols
print('array2 shape:', array2.shape)

array3 = array1.reshape(5,-1) # shape with 5 rows
print('array3.shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3.shape: (5, 2)


In [ ]:
array1 = np.arange(8) # 1차원 배열
array3d = array1.reshape((2,2,2)) # 3차원 배열
print('array3d:\n', array3d.tolist()) # 리스트로 추출

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1) # 2차원 배열
print('array5:\n', array5.tolist()) # 리스트로 추출
print('array5 shape:', array5.shape) 

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1) # 2차원 배열
print('array6:\n', array6.tolist()) # 리스트로 추출
print('array6 shape:', array6.shape) 

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### | 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
---
* 인덱싱을 이용하면 넘파이에서 ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있다.

1. **단일 값 추출:**
```pythone
ndarray[index_value]
```

In [ ]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(1, 10)
print('array1: ', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value: ', value)
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int64'>


In [ ]:
# negative index를 이용해 맨 뒤에서 부터 추출
print('맨 뒤: ', array1[-1], '; 맨 뒤에서 두번째: ', array1[-2])

맨 뒤:  9 ; 맨 뒤에서 두번째:  8


In [ ]:
# index를 이용해 ndarray 데이터 값 수정
array1[0] = 9 # 0번째 값은 9로 바꾼다
array1[8] = 0 # 8번째 값은 0으로 바꾼다
print('array1: ', array1)

array1:  [9 2 3 4 5 6 7 8 0]


In [ ]:
# 다차원 ndarray에서 단일 값 추출 
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3) # 2차원
print(array2d)

print('(row=0, col=0) index 가리키는 값: ', array2d[0,0])
print('(row=0, col=1) index 가리키는 값: ', array2d[0,1])
print('(row=1, col=0) index 가리키는 값: ', array2d[1,0])
print('(row=2, col=2) index 가리키는 값: ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값:  1
(row=0, col=1) index 가리키는 값:  2
(row=1, col=0) index 가리키는 값:  4
(row=2, col=2) index 가리키는 값:  9


2. **slicing**: 연속된 인덱스 상의 ndarray를 추출
```python
ndarray(index_start : index_end)
```


In [3]:
# 시작 인덱스에서  종료 인덱스-1 데이터 반환
array1 = np.arange(start = 1, stop = 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# ':' 기호 앞에 시작 인덱스 생략
array1 = np.arange(1, 10)
array4 = array1[:3]  # 맨 처음부터
print(array4)

# ':' 기호 뒤에 종료 인덱스 생략
array5 = array1[3:] # 맨 마지막까지
print(array5)

# ':' 기호 앞/뒤 인덱스 생략
array6 = array1[:] # 맨 처음부터 마지막까지
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [9]:
#2차원 ndarray 슬라이싱
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] /n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] /n [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [11]:
# 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, '\narray2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) 
array2d[1] shape: (3,)


3. **Fancy indexing**: 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarrray를 반환

In [13]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] =>', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1], 2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


4. **Boolean indexing**: 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터 ndarray를 반환

In [14]:
array1d = np.arange(1,10)

# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [15]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [16]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [17]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### | 행렬의 정렬 - `sort()`와 `argsort()``
---
* 행렬 정렬
  - `np.sort()`: 넘파이에서 sort()를 호출하는 방식으로 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
  - `ndarray.sort()`: 행렬 자체에서 sort()를 호출하는 방식으로 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

In [19]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 반환된 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬: ', org_array) 

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 반환된 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]


In [21]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬: ', sort_array1_desc)

내림차순으로 정렬:  [9 5 3 1]


In [26]:
array2d = np.array([[8,12], [7,1]])
print('원본 행렬:\n', array2d)

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

원본 행렬:
 [[ 8 12]
 [ 7  1]]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬된 행렬의 인덱스 반환하기
    - `np.argsort()`: 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환
    - 넘파이에서는 메타 데이터를 가질 수 없기 때문에 그 활용도가 매우 높음

In [27]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


In [28]:
# 내림차순 정렬 시 
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스: ', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스:  [2 3 0 1]


In [30]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스: ', sort_indices_asc)
print('성적 오름차으로 name_array의 이름 출력: ', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스:  [0 2 4 1 3]
성적 오름차으로 name_array의 이름 출력:  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### | 선형대수 연산 - 행렬 내적과 전치 행렬 구하기 
---
* 행렬 내적(행렬 곱)
```python
np.dot(A, B)
```


In [32]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8], [9,10], [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬: 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
```python
np.transpose(A)
```

In [33]:
A = np.array([[1,2], [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
