<a href="https://colab.research.google.com/github/youngseo21/esaa_22/blob/main/session_112122_regression(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 단순 선형 회귀 분석**
- 전복의 나이를 예측하는 선형회귀모델을 생성하세요.
- 전복의 ‘성별’, ‘키’, ‘지름’, ‘높이’, ‘전체무게’, ‘몸통무게’, ‘내장무게’, ‘껍질무게’를 이용해 ‘껍질의 고리 수’를 예측한 뒤, **예측된 ‘껍질의 고리 수’에 1.5를 더하면 전복의 나이**가 됩니다.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# 기본 모듈 불러오기
import numpy as np
import pandas as pd

**1) 데이터 load 및 변형** 

In [3]:
# 데이터 로드
data = pd.read_csv("/content/drive/MyDrive/esaa_data/abalone (2).csv")
data.head()
print(data.shape)

# 성별 M은 Male, F는 Female, I는 Infant 이므로 따로 열 만들기
for label in "MFI":
    data[label] = data["Sex"] == label
data.drop('Sex', axis=1, inplace=True)

(4177, 9)


In [4]:
data.head()

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  Rings      M      F      I  
0         0.150     15   True  False  False  
1         0.070      7   True  False  False  
2         0.210      9  False   True  False  
3         0.155     10   True  False  False  
4         0.055      7  False  False   True

**2) X, y 선택**
: y는 Rings열, X는 Rings열을 제외한 나머지를 선택하되 전부 실수가 되도록 한다.

In [12]:
# X,y 데이터 선택
y = data['Rings']
X = data.drop('Rings', axis=1).astype(float)

In [16]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Length          4177 non-null   float64
 1   Diameter        4177 non-null   float64
 2   Height          4177 non-null   float64
 3   Whole weight    4177 non-null   float64
 4   Shucked weight  4177 non-null   float64
 5   Viscera weight  4177 non-null   float64
 6   Shell weight    4177 non-null   float64
 7   M               4177 non-null   float64
 8   F               4177 non-null   float64
 9   I               4177 non-null   float64
dtypes: float64(10)
memory usage: 326.5 KB


 **3) train/test set 분리**

In [13]:
# 필요한 모듈 불러오기
from sklearn.model_selection import train_test_split

In [14]:
# train과 test set 분리 (train:test = 7:3 비율로)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)


**4) 선형회귀모델 생성, 모델 예측치 구하기**

In [15]:
#필요한 모듈 불러오기
from sklearn.linear_model import LinearRegression

In [26]:
#선형회귀모델 생성 및 훈련
regr = LinearRegression()
regr.fit(X_train,y_train)

LinearRegression()

In [27]:
# 모델 예측치 구하기
y_pred = regr.predict(X_test)
# 모델 예측치를 활용해 최종적으로 전복의 나이를 예측
age = y_pred+1.5

In [51]:
y_pred

array([13.21875 ,  9.140625, 10.296875, ...,  9.21875 , 18.78125 ,
       11.      ])

In [19]:
age

array([14.71875 , 10.640625, 11.796875, ..., 10.71875 , 20.28125 ,
       12.5     ])

**5) 모델 평가: MSE, RMSE, R2 score, corr 구하기**

In [52]:
#필요한 모듈 불러오기
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
mse

5.006660716955742

- MSE, RMSE 

In [21]:
#mse, rmse
mse = sum((y_test-y_pred)**2)/len(y_test)
rmse = np.sqrt(mse)

print(mse, rmse)

5.006660716955742 2.2375568634016303


- R2 score

In [31]:
#R2 score 측정
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5251203697301645

- 회귀 절편값

In [53]:
#회귀 절편 값
regr.intercept_

-72748926071972.25

- 회귀 계수 값

In [54]:
#회귀 계수 값
regr.coef_

array([-1.70784058e-01,  1.13146223e+01,  7.22843465e+00,  9.07052102e+00,
       -2.00254956e+01, -1.07638569e+01,  9.66537728e+00,  7.27489261e+13,
        7.27489261e+13,  7.27489261e+13])

- 상관계수

Hint: corr 함수 이용.

In [45]:
# 상관계수 구하기
data.corr()

Length  Diameter    Height  Whole weight  Shucked weight  \
Length          1.000000  0.986812  0.827554      0.925261        0.897914   
Diameter        0.986812  1.000000  0.833684      0.925452        0.893162   
Height          0.827554  0.833684  1.000000      0.819221        0.774972   
Whole weight    0.925261  0.925452  0.819221      1.000000        0.969405   
Shucked weight  0.897914  0.893162  0.774972      0.969405        1.000000   
Viscera weight  0.903018  0.899724  0.798319      0.966375        0.931961   
Shell weight    0.897706  0.905330  0.817338      0.955355        0.882617   
Rings           0.556720  0.574660  0.557467      0.540390        0.420884   
M               0.236543  0.240376  0.215459      0.252038        0.251793   
F               0.309666  0.318626  0.298421      0.299741        0.263991   
I              -0.551465 -0.564315 -0.518552     -0.557592       -0.521842   

                Viscera weight  Shell weight     Rings         M         F  \
Length                0.903018      0.897706  0.556720  0.236543  0.309666   
Diameter              0.899724      0.905330  0.574660  0.240376  0.318626   
Height                0.798319      0.817338  0.557467  0.215459  0.298421   
Whole weight          0.966375      0.955355  0.540390  0.252038  0.299741   
Shucked weight        0.931961      0.882617  0.420884  0.251793  0.263991   
Viscera weight        1.000000      0.907656  0.503819  0.242194  0.308444   
Shell weight          0.907656      1.000000  0.627574  0.235391  0.306319   
Rings                 0.503819      0.627574  1.000000  0.181831  0.250279   
M                     0.242194      0.235391  0.181831  1.000000 -0.512528   
F                     0.308444      0.306319  0.250279 -0.512528  1.000000   
I                    -0.556081     -0.546953 -0.436063 -0.522541 -0.464298   

                       I  
Length         -0.551465  
Diameter       -0.564315  
Height         -0.518552  
Whole weight   -0.557592  
Shucked weight -0.521842  
Viscera weight -0.556081  
Shell weight   -0.546953  
Rings          -0.436063  
M              -0.522541  
F              -0.464298  
I               1.000000

In [57]:
Df = pd.DataFrame({'y_pred':y_pred, 'y_test':y_test})
corr = Df.corr()
corr

y_pred    y_test
y_pred  1.000000  0.725099
y_test  0.725099  1.000000

In [46]:
np.corrcoef(y_pred,y_test)

array([[1.       , 0.7250985],
       [0.7250985, 1.       ]])

# **2. Polynomial features**

In [ ]:
# PolynomialFeatures 라이브러리 호출

In [36]:
# 임의 데이터 생성

X = np.arange(6).reshape(3, 2)

df =  pd.DataFrame(X)
df.columns = ['x_1','x_2']
df

x_1  x_2
0    0    1
1    2    3
2    4    5

In [58]:
# 차원은 2로 설정
# fit_transform 메소드를 통해 데이터 변환
# PolynomialFeatures로 변환 된 데이터를 데이터 프레임 형태로 변환
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)

poly_ftr=poly.fit_transform(X)
poly_ftr

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [41]:
# df_poly의 컬럼을 1,x1,x2,x1^2,x1*x2,x2^2 로 변경
df_poly = pd.DataFrame(poly_ftr)
df_poly.columns = ['1','x1','x2','x1^2','x1*x2','x2^2']
df_poly

1   x1   x2  x1^2  x1*x2  x2^2
0  1.0  0.0  1.0   0.0    0.0   1.0
1  1.0  2.0  3.0   4.0    6.0   9.0
2  1.0  4.0  5.0  16.0   20.0  25.0